version: '3.8'

services:
  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=stc_db
      - POSTGRES_USER=stc_user
      - POSTGRES_PASSWORD=stc_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: